---
- name: Get Gitea route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ gitea_customize_gitea_namespace }}"
    name: gitea
  register: r_route

- name: Set Gitea endpoint and url
  set_fact:
    gitea_customize_gitea_endpoint: "{{ r_route.resources[0].spec.host }}"

- name: Import customers-app repository
  uri:
    url: "https://{{ gitea_customize_gitea_endpoint }}/api/v1/repos/migrate"
    user: "{{ gitea_customize_gitea_admin_user }}"
    password: "{{ gitea_customize_gitea_admin_password }}"
    method: POST
    force_basic_auth: true
    validate_certs: false
    body_format: json
    status_code: 201
    headers:
      Content-Type: application/json
    body: >-
      {
      "clone_addr": "{{ item.url }}",
      "repo_name": "{{ item.name }}",
      "repo_owner": "{{ gitea_customize_gitea_admin_user }}",
      "private": false
      }
  loop: "{{ gitea_customize_gitea_public_repos }}"

- name: Apply user templating
  include_tasks: apply_user_templating.yml
  loop: "{{ range(0, gitea_customize_gitea_num_users | int, 1) | list }}"
  loop_control:
    loop_var: n
  vars:
    index: "{{ n | int + 1 }}"
    gitea_username: "{{ gitea_customize_gitea_user_name_base }}{{ index }}