---
- name: Get Gitea route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ argo_customize_gitea_namespace }}"
    name: gitea
  register: r_route

- name: Set Gitea endpoint and url
  set_fact:
    argo_customize_gitea_endpoint: https://{{ r_route.resources[0].spec.host }}

- name: Apply user based templating
  include_tasks: template_user_resources.yml
  loop: "{{ range(0, argo_customize_num_users | int, 1) | list }}"
  loop_control:
    loop_var: n

- name: Apply combined user templating
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'user-ns-rolebinding.yml.j2') | from_yaml }}"
    namespace: "{{ argo_customize_argo_namespace }}"

- name: Patch ArgoCD to add users
  kubernetes.core.k8s_json_patch:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    namespace: "{{ argo_customize_argo_namespace }}"
    name: openshift-gitops
    patch:
      - op: replace
        path: /spec/rbac/defaultPolicy
        value: ''
      - op: replace
        path: /spec/rbac/policy
        value: |
          g, system:cluster-admins, role:admin
          {% for i in range(1, argo_customize_num_users | int + 1) %}
          p, user{{ i }}, projects, get, user{{ i }}, allow
          p, user{{ i }}, applications, get, user{{ i }}/*, allow
          {% endfor %}
      - op: replace
        path: /spec/rbac/scopes
        value: '[groups]'

- name: Patch ArgoCD to add users
  kubernetes.core.k8s_json_patch:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    namespace: "{{ argo_customize_argo_namespace }}"
    name: openshift-gitops
    patch:
      - op: replace
        path: /spec/extraConfig/accounts.user{{ index }}
        value: '[groups]'
  loop: "{{ range(0, argo_customize_num_users | int, 1) | list }}"
  loop_control:
    loop_var: n
  vars:
    index: "{{ n | int + 1 }}"