---
- name: Get Gitea route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ argo_customize_gitea_namespace }}"
    name: gitea
  register: r_route

- name: Set Gitea endpoint and url
  set_fact:
    argo_customize_gitea_endpoint: https://{{ r_route.resources[0].spec.host }}

- name: Apply user based templating
  include_tasks: template_user_resources.yml
  loop: "{{ range(0, argo_customize_num_users | int) | list }}"
  loop_control:
    loop_var: index

