---
- name: Apply user based templating
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', template_file) | from_yaml }}"
    namespace: "{{ argo_customize_argo_namespace }}"
  loop:
  - argocd-customers-repo.yml.j2
  - pod-role.yml.j2
  - user-pod-rolebinding.yml.j2
  - argocd-env-repo.yml.j2
  - argocd-pipeline-repo.yml.j2
  - argocd-project.yml.j2
  - argocd-customers-app.yml.j2
  - argocd-leaderboard-app.yml.j2
  loop_control:
    loop_var: template_file
  vars:
    index: "{{ n | int + 1 }}"